services:
  database:
    image: mysql:latest
    restart: always
    env_file: ./database/.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  http:
    build:
      context: ..
      dockerfile: ./docker/server/Dockerfile
    restart: always
    env_file: ./server/.env
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy