services:
  http:
    build:
      context: ..
      dockerfile: ./docker/server/Dockerfile
    restart: always
    env_file: ./server/.env
    ports:
      - 3000:3000
    volumes:
      - ./autobaan_db:/app/db