services:
  http:
    build:
      context: ..
      dockerfile: ./docker/server/Dockerfile
    restart: always
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    volumes:
      - ../db:/app/db
  redis:
    image: redis
    ports:
      - 6379