name: Push to main
on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/cgduncan7/autobaan:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      #   run: docker build . -f docker/server/Dockerfile -t $GHCR_IMAGE
      # - name: Login to GHCR Docker repo
      #   run: docker login ghcr.io -u $GHCR_USERNAME --password $GHCR_PASSWORD
      # - name: Push docker image
      #   run: docker push $GHCR_IMAGE